M48
; DRILL file {KiCad (6.0.5-0)} date Sunday, March 03, 2024 at 11:29:26 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-03T23:29:26-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X92.775Y-65.925
X92.775Y-123.925
X115.775Y-65.925
X115.775Y-123.925
T0
M30
