M48
; DRILL file {KiCad (6.0.5-0)} date Monday, February 05, 2024 at 06:51:58 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-05T18:51:58-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X89.15Y-65.75
X89.15Y-123.75
X112.15Y-65.75
X112.15Y-123.75
T0
M30
