M48
; DRILL file {KiCad (6.0.5-0)} date Monday, March 04, 2024 at 01:36:47 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-03-04T13:36:47-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.750
%
G90
G05
T1
X88.805Y-65.48
X88.805Y-123.48
X111.805Y-65.48
X111.805Y-123.48
T0
M30
